### ISSUE TITLE
missing image

### ISSUE THREAD

**Issue by samant-rags** [Azure/sterling#9]
![image](https://user-images.githubusercontent.com/5258222/207218491-a91d8964-7521-4c5a-a0f2-05b661c82204.png)

link to image is not proper : https://raw.githubusercontent.com/Azure/sterling/main/docs/images/SterlingNetworkDiagram.png

**Comment by drewfurgiuele** [comment]
The document has been updated with a fixed image link (and a new diagram as well). Thanks for letting us know!
